### PR TITLE
Rework archlinux packaging

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
Missing python-setuptools (or whatever the package name is on Arch):
```
21:13:20,905 [executor:docker:a646b6ef2c] output:     from setuptools import setup, Extension.
21:13:20,906 [executor:docker:a646b6ef2c] output: ModuleNotFoundError: No module named 'setuptools'.
```

**Comment by fepitre** [comment]
PipelineRetry

**Review by marmarek — APPROVED** [review]

**Pull request merged**
