### PR TITLE
rpmbuild: fix build error for empty debug files

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by marmarek** [comment]
Why is it needed? There should be debug package produced, with debug symbols to libqubesdb.so.

**Comment by fepitre** [comment]
When building for Fedora27, it complains about empty debug files. Maybe something needs to be adjusted.

**Comment by fepitre** [comment]
Ok. At first instance, I thought it was because there were not specific debug package. With respect to Fedora 27, I find what was the problem (https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/ITJHJTUO2WFEAYIHANSM6AMAB5SIFASI/). It seems to be a bug from newer default rpm macros: 

%global _debugsource_packages 1
%global _debuginfo_subpackages 1

I put %undefine _debugsource_packages and it builds now fine.

**Comment by marmarek** [comment]
Does it mean our packaging is buggy and does not have sources in expected location? I think previously debuginfo package for qubesdb did contains source files... But apparently the package currently in repo does not have debuginfo at all :/

**Comment by marmarek** [comment]
Ok, definitely our packaging is buggy. It is result of this hack:
```
%prep
# we operate on the current directory, so no need to unpack anything
# symlink is to generate useful debuginfo packages
rm -f %{name}-%{version}
ln -sf . %{name}-%{version}
%setup -T -D
```
This means, the source root dir is a symlink. And find-debuginfo does not handle it. I have some work-in-progress code to generate proper source tarballs and get rid of this hack. It looks like it's the time to finally finish it...

**Comment by marmarek** [comment]
This is tracked by https://github.com/QubesOS/qubes-issues/issues/1508

**Comment by fepitre** [comment]
Maybe a dumb question but have you try hard link instead of symlink?(temp hack...)

**Comment by marmarek** [comment]
hardlink isn't possible on directory

**Comment by fepitre** [comment]
So how do we do for Fedora 27? we wait for your changes with tarballs?

**Comment by marmarek** [comment]
Yes. I'll push something tomorrow (either finished version, or at least the work-in-progress one).

**Pull request closed without merging**
